services:
  dhr-landsat-httpServer:
    #build: ./
    image: ghcr.io/matejkaj-cesnet/dhr-landsat-httpserver-ghcr:latest
    #volumes:
    #  - ./:/app
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
