name: Docker Image CI; Create GHCR Package

on:
  push

permissions:
  contents: read
  packages: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GHCR
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GHCRPAT_DHRDOWNLOADSTACRELAY }}

      - name: Build and push the image
        run: |
          docker build . --tag ghcr.io/${{ github.actor }}/dhr-download-stac-relay:latest
          docker push ghcr.io/${{ github.actor }}/dhr-download-stac-relay:latest
